# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  body_converter:
    enabled: true
    validate: true
    validation_errors_argument: violations
    #    allowed_methods_listener:  true
    #    routing_loader: true
  exception:
    enabled: true
    exception_controller: 'fos_rest.exception.controller:showAction'
  format_listener:
    rules:
      - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json, html ] }
      - { path: ^/login, prefer_extension: true, fallback_format: json, priorities: [ json, html ] }

  param_fetcher_listener:  force
  serializer:
    serialize_null: true
  versioning:
    enabled: true
    default_version: '1.0'
    resolvers:
      media_type: #Accept header
        enabled: true
        regex: '/(version)=(?P<version>[0-9\.]+)/'
  view:
    view_response_listener:  true
    mime_types:
      json: ['application/json']
