nelmio_api_doc:
    documentation:
        host: 127.0.0.1:8000
        schemes: [http, https]
        info:
            title: API BileMo
            description: This is tool for BileMo customers.
            version: 0.3.0
        securityDefinitions:
            Bearer:
                type: apiKey
                description: 'Value: Bearer {OAuth2}'
                name: X-AUTH-TOKEN
                in: header
        security:
            - Bearer: []
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc)(?!/admin) # Accepts routes under /api except /api/doc, /api/admin

