nelmio_api_doc:
    documentation:
        host: 127.0.0.1:8000
        schemes: [http, https]
        info:
            title: API BileMo
            description: Api for of Bilemo inc clients. List/detail of phones and users. Can manage Users to. Implements the client manager for administrators.
            version: 0.7.3
        securityDefinitions:
            Bearer:
                type: apiKey
                description: 'Value: Bearer {OAuth2}'
                name: X-AUTH-TOKEN
                in: header
        security:
            - Bearer: []
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc)(?!/admin) # Accepts routes under /api except /api/doc, /api/admin

